const ROOM_OPTIONS=["Main Entrance","Living / Dining","Kitchen","Balcony","Storeroom","Utility Yard","Bedroom 1","Bedroom 2","Bedroom 3","Bedroom 4","Bathroom 1","Bathroom 2","Bathroom 3","Bathroom 4"];
const GENERAL_ITEMS=["Floor","Wall","Door & Locks","Lighting","Ceiling Fan","Aircon","Sensor","Wardrobe / Cabinets / Drawers","Windows & Lock","Curtain / Blinds"];
const CHECKLIST={
  "Main Entrance":["Floor","Wall","Door & Locks","Bell","Lighting","Sensor","Wardrobe / Cabinets / Drawers","Windows & Lock","Curtain / Blinds"],
  "Living / Dining":GENERAL_ITEMS,
  "Kitchen":["Floor","Wall","Door & Locks","Bell","Lighting","Ceiling Fan","Aircon","Sensor","Cabinets / Drawers","Windows & Lock","Curtain / Blinds","Water Heater","Sink","Hob","Hood","Oven","Microwave","Fridge","Washer / Washer cum dryer","Dryer","Dishwasher","Wine Cellar"],
  "Balcony":["Floor","Wall","Door & Locks","Lighting","Ceiling Fan","Water Tap","Blinds / Ziptrak"],
  "Storeroom":["Floor","Wall","Lighting","Door & Locks"],
  "Utility Yard":["Floor","Wall","Lighting","Ceiling Fan","Laundry Rack","Door & Locks"],
  "Bedroom 1":GENERAL_ITEMS,"Bedroom 2":GENERAL_ITEMS,"Bedroom 3":GENERAL_ITEMS,"Bedroom 4":GENERAL_ITEMS,
  "Bathroom 1":["Floor","Wall","Door & Locks","Lighting","Ventilator","Ceiling Fan","Water Tap","Curtain / Blinds","Windows & Lock","Cabinets / Drawers","Water Heater","Basin Tap and Stopper","WC Flush","Shower Head and Hose","Bathtub Tap and Hose"],
  "Bathroom 2":[],"Bathroom 3":[],"Bathroom 4":[]
};
CHECKLIST["Bathroom 2"]=[...CHECKLIST["Bathroom 1"]];CHECKLIST["Bathroom 3"]=[...CHECKLIST["Bathroom 1"]];CHECKLIST["Bathroom 4"]=[...CHECKLIST["Bathroom 1"]];
const FLOOR_CONDITIONS=["Existing Condition (Not Polished / Varnished)","Polished / Varnished Condition","Others","Not applicable"];
const WALL_CONDITIONS=["Existing Condition (Not Repainted)","Repainted","Touch up","Others","Not applicable"];
const WORKING_CONDITIONS=["Working Condition","Others","Not applicable"];
const conditionsFor=item=>item==="Floor"?FLOOR_CONDITIONS:item==="Wall"?WALL_CONDITIONS:WORKING_CONDITIONS;
const defaultCondition=item=>conditionsFor(item)[0];
const $=id=>document.getElementById(id); let reports=[],current=null,currentStep="details",editingObservation=null,tempPhotos=[],annotationIndex=-1,drawState=null,annotationTool="circle",annotationHistory=[];

const DB={
  open(){return new Promise((resolve,reject)=>{const r=indexedDB.open("HandoverX",1);r.onupgradeneeded=()=>r.result.createObjectStore("reports",{keyPath:"id"});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})},
  async all(){const db=await this.open();return new Promise((resolve,reject)=>{const r=db.transaction("reports").objectStore("reports").getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})},
  async put(value){const db=await this.open();return new Promise((resolve,reject)=>{const r=db.transaction("reports","readwrite").objectStore("reports").put(value);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})},
  async delete(id){const db=await this.open();return new Promise((resolve,reject)=>{const r=db.transaction("reports","readwrite").objectStore("reports").delete(id);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})}
};
const uid=()=>crypto.randomUUID?.()||`HX-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const today=()=>new Date().toISOString().slice(0,10);
const dateKey=value=>{const s=String(value||"").trim();if(/^\d{8}$/.test(s))return s;if(/^\d{4}-\d{2}-\d{2}/.test(s))return`${s.slice(8,10)}${s.slice(5,7)}${s.slice(0,4)}`;return s.replace(/\D/g,"").slice(0,8)};
const todayKey=()=>{const d=new Date();return`${String(d.getDate()).padStart(2,"0")}${String(d.getMonth()+1).padStart(2,"0")}${d.getFullYear()}`};
const validDateKey=value=>{const key=dateKey(value);if(!/^\d{8}$/.test(key))return false;const day=Number(key.slice(0,2)),month=Number(key.slice(2,4)),year=Number(key.slice(4)),d=new Date(year,month-1,day);return d.getFullYear()===year&&d.getMonth()===month-1&&d.getDate()===day};
const formatDate=value=>{const key=dateKey(value);if(!validDateKey(key))return key;const day=key.slice(0,2),month=Number(key.slice(2,4)),year=key.slice(4),months=["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"];return`${day}-${months[month-1]}-${year}`};
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function newReport(){return{id:uid(),title:"Condition Report",address:"",handoverDate:todayKey(),preparedFor:"",preparedBy:"",generalNotes:"",selectedRooms:["Main Entrance","Living / Dining","Kitchen","Bedroom 1","Bathroom 1"],customRoomNames:[],checklist:{},observations:[],version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove("show"),2400)}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function slug(s){return(s||"property").replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").slice(0,50)}
async function saveCurrent(show=false){if(!current)return;syncForm();current.updatedAt=new Date().toISOString();await DB.put(current);const i=reports.findIndex(r=>r.id===current.id);if(i>=0)reports[i]=current;else reports.push(current);$("saveStatus").textContent="Saved on this device";if(show)toast("Report saved on this device")}
let saveTimer;function queueSave(){if(!current)return;$("saveStatus").textContent="Saving…";clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveCurrent(),350)}
function syncForm(){if(!current)return;current.title="Condition Report";current.address=$("address").value.trim();current.handoverDate=dateKey($("handoverDate").value);current.preparedFor=$("preparedFor").value.trim();current.preparedBy=$("preparedBy").value.trim();current.generalNotes=$("generalNotes").value.trim()}

function showHome(){saveCurrent();current=null;$("homeView").hidden=false;$("editorView").hidden=true;renderReports()}
function migrateReport(report){report.title="Condition Report";report.handoverDate=dateKey(report.handoverDate||report.date||todayKey());report.selectedRooms??=Object.keys(report.checklist||{}).filter(room=>ROOM_OPTIONS.includes(room));if(!report.selectedRooms.length)report.selectedRooms=["Main Entrance","Living / Dining","Kitchen","Bedroom 1","Bathroom 1"];report.customRoomNames??=report.selectedRooms.filter(room=>!ROOM_OPTIONS.includes(room));report.observations??=[];report.checklist??={};return report}
function updateDatePreview(){const key=dateKey($("handoverDate").value);$("handoverDate").value=key;$("handoverDateDisplay").textContent=validDateKey(key)?`Displays as ${formatDate(key)}`:key.length?"Enter a valid date as DDMMYYYY":"Enter as DDMMYYYY";$("handoverDateDisplay").classList.toggle("invalid",!!key&&!validDateKey(key))}
function openEditor(report,step="details"){current=migrateReport(structuredClone(report));$("homeView").hidden=true;$("editorView").hidden=false;$("address").value=current.address||"";$("handoverDate").value=current.handoverDate||todayKey();updateDatePreview();$("preparedFor").value=current.preparedFor||"";$("preparedBy").value=current.preparedBy||"";$("generalNotes").value=current.generalNotes||"";renderRoomSelector();renderChecklist();renderObservations();goStep(step)}
async function createReport(){const report=newReport();await DB.put(report);reports.push(report);openEditor(report)}
function renderReports(filter=""){const q=filter.toLowerCase().trim();const list=reports.filter(r=>`Condition Report ${r.address}`.toLowerCase().includes(q)).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));$("reportList").innerHTML=list.map(r=>`<article class="report-card"><span class="report-type">CONDITION REPORT</span><h3>Condition Report</h3><p>${esc(r.address||"Address not entered")}</p><div class="report-meta"><span>${formatDate(r.handoverDate||r.date||r.createdAt)}</span><span>${r.observations?.length||0} observations</span></div><div class="card-actions"><button class="button secondary" data-open="${r.id}">Open report</button><button class="delete-button" data-delete="${r.id}" aria-label="Delete">Delete</button></div></article>`).join("");$("emptyState").hidden=reports.length>0||q;$("reportList").hidden=!list.length;document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openEditor(reports.find(r=>r.id===b.dataset.open)));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=async()=>{const r=reports.find(x=>x.id===b.dataset.delete);if(confirm("Delete this Condition Report? This cannot be undone unless you have a backup.")){await DB.delete(r.id);reports=reports.filter(x=>x.id!==r.id);renderReports($("searchReports").value);toast("Report deleted")}})}
function goStep(step){currentStep=step;["details","checklist","observations","review"].forEach((s,i)=>{ $(`${s}Panel`).hidden=s!==step;const b=document.querySelector(`.step[data-step="${s}"]`);b.classList.toggle("active",s===step);if(s===step){$("mobileStepTitle").textContent=b.querySelector("strong").textContent;$("mobileStepCount").textContent=`${i+1} of 4`}});if(step==="review")renderReview();scrollTo({top:0,behavior:"smooth"})}
function renderRoomSelector(){current.selectedRooms??=[];current.customRoomNames??=[];const all=[...ROOM_OPTIONS,...current.customRoomNames];$("roomSelector").innerHTML=all.map(room=>`<label class="room-choice"><input type="checkbox" value="${esc(room)}" ${current.selectedRooms.includes(room)?"checked":""}><span>${esc(room)}</span></label>`).join("");$("roomSelector").querySelectorAll("input").forEach(input=>input.onchange=()=>{if(input.checked&&!current.selectedRooms.includes(input.value))current.selectedRooms.push(input.value);if(!input.checked)current.selectedRooms=current.selectedRooms.filter(r=>r!==input.value);renderChecklist();queueSave()})}
function addRoomSelection(){const name=$("customRoomName").value.trim();if(!name)return toast("Enter a room name");if(!current.customRoomNames.includes(name))current.customRoomNames.push(name);if(!current.selectedRooms.includes(name))current.selectedRooms.push(name);$("customRoomName").value="";renderRoomSelector();renderChecklist();queueSave();toast("Room added to this report")}
function renderChecklist(){const keys=current.selectedRooms||[];if(!keys.length){$("checklistRooms").innerHTML='<div class="empty-state compact"><div class="empty-icon">⌂</div><h3>Choose rooms first</h3><p>Return to Property details and select the rooms included in this report.</p></div>';return}$("checklistRooms").innerHTML=keys.map((room,idx)=>{const items=CHECKLIST[room]||GENERAL_ITEMS;current.checklist[room]??={};items.forEach(item=>{current.checklist[room][item]??={condition:defaultCondition(item),note:""};if(!current.checklist[room][item].condition)current.checklist[room][item].condition=defaultCondition(item)});return`<details class="room-card" ${idx<2?'open':''}><summary>${esc(room)}</summary><div class="room-items">${items.map(item=>{const v=current.checklist[room][item],conditions=conditionsFor(item);return`<div class="check-row"><span>${esc(item)}</span><select data-check-room="${esc(room)}" data-check-item="${esc(item)}">${conditions.map(c=>`<option ${v.condition===c?'selected':''}>${esc(c)}</option>`).join('')}</select><input data-note-room="${esc(room)}" data-note-item="${esc(item)}" value="${esc(v.note||'')}" placeholder="Write a comment if needed" /></div>`}).join('')}</div></details>`}).join("");document.querySelectorAll("[data-check-room]").forEach(el=>el.onchange=()=>updateCheck(el.dataset.checkRoom,el.dataset.checkItem,"condition",el.value));document.querySelectorAll("[data-note-room]").forEach(el=>el.oninput=()=>updateCheck(el.dataset.noteRoom,el.dataset.noteItem,"note",el.value));queueSave()}
function updateCheck(room,item,key,value){current.checklist[room]??={};current.checklist[room][item]??={};current.checklist[room][item][key]=value;queueSave()}

function renderObservations(){const list=current.observations||[];$("observationEmpty").hidden=!!list.length;$("observationList").innerHTML=list.map((o,i)=>`<article class="observation-card"><div class="observation-head"><div><span class="room-chip">${esc(o.room)}</span><h3>${esc(o.comment)}</h3></div><div class="observation-actions"><button data-edit-observation="${i}">Edit</button><button data-remove-observation="${i}">Delete</button></div></div>${o.photos?.length?`<div class="observation-photos">${o.photos.map(p=>`<img src="${p.data}" alt="Condition evidence" />`).join('')}</div>`:''}</article>`).join("");document.querySelectorAll("[data-edit-observation]").forEach(b=>b.onclick=()=>openObservation(Number(b.dataset.editObservation)));document.querySelectorAll("[data-remove-observation]").forEach(b=>b.onclick=()=>{if(confirm("Delete this observation?")){current.observations.splice(Number(b.dataset.removeObservation),1);renderObservations();queueSave()}})}
function openObservation(index=null){if(!current.selectedRooms?.length)return toast("Choose at least one room in Property details first");editingObservation=index;const o=index===null?{room:current.selectedRooms[0],comment:"",photos:[]} : current.observations[index];tempPhotos=structuredClone(o.photos||[]);$("observationDialogTitle").textContent=index===null?"Add observation":"Edit observation";const rooms=[...current.selectedRooms];if(o.room&&!rooms.includes(o.room))rooms.push(o.room);$("observationRoom").innerHTML=rooms.map(r=>`<option ${o.room===r?'selected':''}>${esc(r)}</option>`).join("");$("observationComment").value=o.comment||"";renderTempPhotos();$("observationDialog").showModal()}
function renderTempPhotos(){$("photoPreview").innerHTML=tempPhotos.map((p,i)=>`<div class="photo-tile"><img src="${p.data}" alt="Selected photo"><div class="photo-tile-actions"><button type="button" data-annotate="${i}">Mark up</button><button type="button" data-remove-photo="${i}">Remove</button></div></div>`).join("");document.querySelectorAll("[data-remove-photo]").forEach(b=>b.onclick=()=>{tempPhotos.splice(Number(b.dataset.removePhoto),1);renderTempPhotos()});document.querySelectorAll("[data-annotate]").forEach(b=>b.onclick=()=>openAnnotation(Number(b.dataset.annotate)))}
async function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=1800,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);resolve({id:uid(),name:file.name,data:canvas.toDataURL("image/jpeg",.82),annotated:false})};img.onerror=reject;img.src=url})}
async function addPhotos(files){const remaining=3-tempPhotos.length;if(remaining<=0)return toast("Maximum three photos per observation");for(const file of [...files].slice(0,remaining))tempPhotos.push(await compressImage(file));renderTempPhotos();if(files.length>remaining)toast("Only the first available photos were added")}
function saveObservation(e){e.preventDefault();const room=$("observationRoom").value,comment=$("observationComment").value.trim();if(!room)return toast("Choose a room or area");if(!comment)return toast("Enter an observation comment");const value={id:editingObservation===null?uid():current.observations[editingObservation].id,room,comment,photos:tempPhotos};if(editingObservation===null)current.observations.push(value);else current.observations[editingObservation]=value;$("observationDialog").close();renderObservations();queueSave();toast("Observation saved")}

function openAnnotation(index){annotationIndex=index;annotationHistory=[];const img=new Image();img.onload=()=>{const canvas=$("annotationCanvas"),maxW=1200,maxH=850,scale=Math.min(1,maxW/img.width,maxH/img.height);canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);annotationHistory.push(canvas.toDataURL());$("annotationDialog").showModal()};img.src=tempPhotos[index].data}
function canvasPoint(e){const c=$("annotationCanvas"),r=c.getBoundingClientRect(),t=e.touches?.[0]||e;return{x:(t.clientX-r.left)*c.width/r.width,y:(t.clientY-r.top)*c.height/r.height}}
function annotationStart(e){e.preventDefault();drawState={start:canvasPoint(e),base:$("annotationCanvas").toDataURL(),points:[canvasPoint(e)]}}
function annotationMove(e){if(!drawState)return;e.preventDefault();const c=$("annotationCanvas"),ctx=c.getContext("2d"),p=canvasPoint(e),img=new Image();img.onload=()=>{ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(img,0,0);ctx.strokeStyle=$("annotationColor").value;ctx.fillStyle=$("annotationColor").value;ctx.lineWidth=Math.max(4,c.width/180);ctx.lineCap="round";if(annotationTool==="draw"){drawState.points.push(p);ctx.beginPath();ctx.moveTo(drawState.points[0].x,drawState.points[0].y);drawState.points.slice(1).forEach(q=>ctx.lineTo(q.x,q.y));ctx.stroke()}else if(annotationTool==="circle"){const x=(drawState.start.x+p.x)/2,y=(drawState.start.y+p.y)/2,rx=Math.abs(p.x-drawState.start.x)/2,ry=Math.abs(p.y-drawState.start.y)/2;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.stroke()}else{ctx.beginPath();ctx.moveTo(drawState.start.x,drawState.start.y);ctx.lineTo(p.x,p.y);ctx.stroke();const angle=Math.atan2(p.y-drawState.start.y,p.x-drawState.start.x),size=18+c.width/100;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x-size*Math.cos(angle-Math.PI/6),p.y-size*Math.sin(angle-Math.PI/6));ctx.lineTo(p.x-size*Math.cos(angle+Math.PI/6),p.y-size*Math.sin(angle+Math.PI/6));ctx.closePath();ctx.fill()}};img.src=drawState.base}
function annotationEnd(){if(!drawState)return;annotationHistory.push($("annotationCanvas").toDataURL());drawState=null}
function restoreCanvas(data){const img=new Image();img.onload=()=>{$("annotationCanvas").getContext("2d").drawImage(img,0,0)};img.src=data}

function renderReview(){syncForm();const checked=(current.selectedRooms||[]).reduce((n,room)=>n+Object.values(current.checklist?.[room]||{}).filter(x=>x.condition).length,0),photos=current.observations.reduce((n,o)=>n+(o.photos?.length||0),0);$("reviewSummary").innerHTML=`<div class="summary-card"><span>Checklist items</span><strong>${checked}</strong></div><div class="summary-card"><span>Observations</span><strong>${current.observations.length}</strong></div><div class="summary-card"><span>Photos</span><strong>${photos}</strong></div><div class="summary-card report-overview"><span>Report</span><strong>Condition Report</strong><p>${esc(current.address||"Address not entered")} · Handover ${formatDate(current.handoverDate)}</p></div>`}
async function sha(text){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return[...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function generatePdf(){if(!current.address)return toast("Add the property address before exporting");if(!validDateKey(current.handoverDate))return toast("Enter a valid handover date as DDMMYYYY");if(!current.selectedRooms?.length)return toast("Choose at least one room before exporting");await saveCurrent();const {PDFDocument,StandardFonts,rgb}=PDFLib,pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),W=595,H=842,margin=48,green=rgb(.07,.21,.18),rust=rgb(.78,.36,.23),ink=rgb(.08,.14,.12),muted=rgb(.37,.43,.40),line=rgb(.84,.85,.82);let page,y;
  const addPage=()=>{page=pdf.addPage([W,H]);y=H-70;page.drawText("HANDOVERX",{x:margin,y:H-31,size:8,font:bold,color:green});page.drawLine({start:{x:margin,y:H-39},end:{x:W-margin,y:H-39},thickness:.6,color:line});return page};
  const ensure=h=>{if(y-h<44)addPage()};const wrap=(text,max,size=10,f=regular)=>{const words=String(text||"").replace(/[^\x20-\x7E]/g,"-").split(/\s+/),lines=[];let l="";for(const w of words){const n=l?`${l} ${w}`:w;if(f.widthOfTextAtSize(n,size)>max){if(l)lines.push(l);l=w}else l=n}if(l)lines.push(l);return lines};const text=(value,x,size=10,f=regular,color=ink,max=W-margin*2,leading=size*1.35)=>{const lines=wrap(value,max,size,f);ensure(lines.length*leading+4);for(const l of lines){page.drawText(l,{x,y,size,font:f,color});y-=leading}return lines.length};const label=value=>{ensure(26);page.drawText(value.toUpperCase(),{x:margin,y,size:7.5,font:bold,color:rust});y-=17};const heading=value=>{ensure(36);text(value,margin,18,bold,ink);y-=8};
  page=pdf.addPage([W,H]);page.drawRectangle({x:0,y:0,width:W,height:H,color:green});page.drawText("HANDOVERX",{x:margin,y:H-65,size:12,font:bold,color:rgb(.78,.92,.87)});page.drawText("RESIDENTIAL",{x:margin,y:H-205,size:11,font:bold,color:rgb(.55,.78,.70)});page.drawText("CONDITION",{x:margin,y:H-254,size:38,font:bold,color:rgb(1,1,1)});page.drawText("REPORT",{x:margin,y:H-299,size:38,font:bold,color:rgb(1,1,1)});let coverY=H-370;for(const l of wrap(current.address,W-margin*2,15,bold)){page.drawText(l,{x:margin,y:coverY,size:15,font:bold,color:rgb(.9,.94,.92)});coverY-=21}page.drawLine({start:{x:margin,y:92},end:{x:W-margin,y:92},thickness:.7,color:rgb(.35,.55,.48)});page.drawText(`Handover date  ${formatDate(current.handoverDate)}`,{x:margin,y:61,size:9,font:regular,color:rgb(.72,.83,.79)});
  addPage();page.drawText("REPORT INFORMATION",{x:margin,y,size:23,font:bold,color:rust});y-=44;const fields=[["PROPERTY ADDRESS",current.address],["HANDOVER DATE",formatDate(current.handoverDate)],["PREPARED FOR",current.preparedFor||"Not stated"],["PREPARED BY",current.preparedBy||"Not stated"],["ROOMS INCLUDED",current.selectedRooms.join(", ")]];for(const [k,v] of fields){ensure(48);page.drawText(k,{x:margin,y,size:7.5,font:bold,color:muted});text(v,margin+112,10,bold,ink,W-margin*2-112);y-=11}if(current.generalNotes){y-=8;label("General notes");text(current.generalNotes,margin,9.5,regular,ink);y-=10}
  const activeRooms=current.selectedRooms.map(room=>[room,current.checklist?.[room]||{}]);if(activeRooms.length){ensure(48);page.drawText("ROOM CHECKLIST",{x:margin,y,size:23,font:bold,color:rust});y-=38;for(const [room,items] of activeRooms){ensure(42);text(room,margin,12,bold,green);y-=5;for(const [item,v] of Object.entries(items)){ensure(v.note?32:22);page.drawText(item,{x:margin,y,size:8.5,font:bold,color:ink});page.drawText(v.condition||defaultCondition(item),{x:margin+165,y,size:8.2,font:regular,color:green});y-=13;if(v.note){for(const noteLine of wrap(`Note: ${v.note}`,W-margin-165,8.2,regular)){page.drawText(noteLine,{x:margin+165,y,size:8.2,font:regular,color:muted});y-=11}}y-=4}y-=9}}
  if(current.observations.length){const observationHeader=()=>{addPage();page.drawText("PHOTO OBSERVATIONS",{x:margin,y,size:23,font:bold,color:rust});y-=44};observationHeader();for(let i=0;i<current.observations.length;i++){if(i>0&&i%3===0)observationHeader();const o=current.observations[i],blockH=205,photoX=margin,photoW=302,photoH=154,commentX=margin+322,commentW=W-margin-commentX;ensure(blockH);page.drawText(o.room.toUpperCase(),{x:margin,y,size:12,font:bold,color:green});y-=22;const frameY=y-photoH;if(o.photos?.length){const count=Math.min(3,o.photos.length),gap=6,cellW=(photoW-gap*(count-1))/count;for(let pIndex=0;pIndex<count;pIndex++){const x=photoX+pIndex*(cellW+gap);page.drawRectangle({x,y:frameY,width:cellW,height:photoH,color:rgb(.95,.95,.93)});try{const photo=o.photos[pIndex],bytes=await fetch(photo.data).then(r=>r.arrayBuffer()),img=photo.data.startsWith("data:image/png")?await pdf.embedPng(bytes):await pdf.embedJpg(bytes),dims=img.scale(1),scale=Math.min((cellW-6)/dims.width,(photoH-6)/dims.height),dw=dims.width*scale,dh=dims.height*scale;page.drawImage(img,{x:x+(cellW-dw)/2,y:frameY+(photoH-dh)/2,width:dw,height:dh})}catch{}}}const commentLines=wrap(o.comment,commentW,9,regular),commentLeading=12,commentY=frameY+(photoH+commentLines.length*commentLeading)/2-commentLeading;commentLines.forEach((l,lineIndex)=>page.drawText(l,{x:commentX,y:commentY-lineIndex*commentLeading,size:9,font:regular,color:ink}));y=frameY-25;}}
  const bytes=await pdf.save();download(new Blob([bytes],{type:"application/pdf"}),`HandoverX_${slug(current.address)}_${slug(current.title)}_v${current.version}.pdf`);current.version=(current.version||1)+1;await saveCurrent();toast("PDF downloaded")}

function exportData(data,name){download(new Blob([JSON.stringify({app:"HandoverX",exportedAt:new Date().toISOString(),reports:data},null,2)],{type:"application/json"}),name)}
async function importData(file){try{const json=JSON.parse(await file.text()),incoming=Array.isArray(json.reports)?json.reports:[json.reports];if(!incoming.length)throw Error();for(const r of incoming){if(!r?.id)r.id=uid();await DB.put(r);const i=reports.findIndex(x=>x.id===r.id);if(i>=0)reports[i]=r;else reports.push(r)}renderReports();toast(`${incoming.length} report${incoming.length===1?'':'s'} restored`)}catch{toast("That backup file could not be read")}}

function bind(){[$("newReportTop"),$("newReportHero"),$("emptyCreate")].forEach(b=>b.onclick=createReport);$("backHome").onclick=$("mobileBack").onclick=showHome;document.querySelectorAll(".step").forEach(b=>b.onclick=()=>{saveCurrent();goStep(b.dataset.step)});document.querySelectorAll("[data-next]").forEach(b=>b.onclick=()=>{saveCurrent();goStep(b.dataset.next)});document.querySelectorAll("[data-prev]").forEach(b=>b.onclick=()=>goStep(b.dataset.prev));["address","handoverDate","preparedFor","preparedBy","generalNotes"].forEach(id=>$(id).addEventListener("input",queueSave));$("addRoomSelection").onclick=addRoomSelection;$("customRoomName").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();addRoomSelection()}};$("searchReports").oninput=e=>renderReports(e.target.value);$("addObservation").onclick=$("emptyAddObservation").onclick=()=>openObservation();$("photoInput").onchange=e=>addPhotos(e.target.files);$("saveObservation").onclick=saveObservation;$("generatePdf").onclick=generatePdf;$("finishReport").onclick=showHome;$("duplicateReport").onclick=async()=>{const copy=structuredClone(current);copy.id=uid();copy.title="Condition Report";copy.version=1;copy.createdAt=copy.updatedAt=new Date().toISOString();await DB.put(copy);reports.push(copy);openEditor(copy);toast("Separate report created")};$("backupReport").onclick=()=>exportData([current],`HandoverX_${slug(current.address)}_backup.handoverx`);$("backupAll").onclick=()=>exportData(reports,"HandoverX_all_reports_backup.handoverx");$("importButton").onclick=()=>$("importInput").click();$("importInput").onchange=e=>importData(e.target.files[0]);$("annotationCanvas").addEventListener("pointerdown",annotationStart);$("annotationCanvas").addEventListener("pointermove",annotationMove);window.addEventListener("pointerup",annotationEnd);document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{annotationTool=b.dataset.tool;document.querySelectorAll("[data-tool]").forEach(x=>x.classList.toggle("active",x===b))});$("undoAnnotation").onclick=()=>{if(annotationHistory.length>1){annotationHistory.pop();restoreCanvas(annotationHistory.at(-1))}};$("clearAnnotation").onclick=()=>{annotationHistory=[annotationHistory[0]];restoreCanvas(annotationHistory[0])};$("saveAnnotation").onclick=()=>{tempPhotos[annotationIndex].data=$("annotationCanvas").toDataURL("image/jpeg",.9);tempPhotos[annotationIndex].annotated=true;$("annotationDialog").close();renderTempPhotos();toast("Photo markup saved")};[$("closeAnnotation"),$("cancelAnnotation")].forEach(b=>b.onclick=()=>$("annotationDialog").close());document.querySelector(".brand").onclick=showHome;window.addEventListener("beforeunload",()=>{if(current)DB.put(current)})}
async function init(){bind();$("handoverDate").addEventListener("input",e=>{e.target.value=dateKey(e.target.value);updateDatePreview();queueSave()});$("handoverDate").addEventListener("blur",updateDatePreview);try{reports=await DB.all();renderReports();if(navigator.storage?.persist)navigator.storage.persist();if("serviceWorker"in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("./service-worker.js")}catch(e){console.error(e);toast("Local storage is unavailable in this browser")}}
init();
