const ROOMS = ["Main entrance / lobby","Living & dining","Main balcony","Kitchen","Bedroom 1","Bedroom 2","Bedroom 3","Bathroom 1","Bathroom 2","Utility / yard","Others"];
const CHECKLIST = {
  "Main entrance / lobby":["Floor","Walls","Door & locks","Doorbell","Lighting","Cabinets / drawers","Windows / locks"],
  "Living & dining":["Floor","Walls","Lighting","Ceiling fan","Air-conditioning","Cabinets / drawers","Windows / locks","Curtains / blinds"],
  "Main balcony":["Floor","Walls","Door & locks","Lighting","Water tap","Blinds / awning"],
  "Kitchen":["Floor","Walls","Door & locks","Lighting","Cabinets / drawers","Sink & strainer","Hob / igniter","Hood / lights","Oven","Refrigerator","Washer / dryer"],
  "Bedroom 1":["Floor","Walls","Door & locks","Lighting","Ceiling fan","Air-conditioning","Wardrobe / drawers","Windows / locks","Curtains / blinds"],
  "Bedroom 2":["Floor","Walls","Door & locks","Lighting","Ceiling fan","Air-conditioning","Wardrobe / drawers","Windows / locks","Curtains / blinds"],
  "Bedroom 3":["Floor","Walls","Door & locks","Lighting","Ceiling fan","Air-conditioning","Wardrobe / drawers","Windows / locks","Curtains / blinds"],
  "Bathroom 1":["Floor","Walls","Door & locks","Lighting","Air vent","Cabinets / drawers","Water heater","Basin / tap","WC flush","Shower head / hose"],
  "Bathroom 2":["Floor","Walls","Door & locks","Lighting","Air vent","Cabinets / drawers","Water heater","Basin / tap","WC flush","Shower head / hose"],
  "Utility / yard":["Floor","Walls","Lighting","Windows / locks","Water tap","Drying rack"]
};
const CONDITIONS=["","Working / good","Existing wear","Defect noted","Not tested","Not applicable"];
const $=id=>document.getElementById(id); let reports=[],current=null,currentStep="details",editingObservation=null,tempPhotos=[],annotationIndex=-1,drawState=null,annotationTool="circle",annotationHistory=[];

const DB={
  open(){return new Promise((resolve,reject)=>{const r=indexedDB.open("HandoverX",1);r.onupgradeneeded=()=>r.result.createObjectStore("reports",{keyPath:"id"});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})},
  async all(){const db=await this.open();return new Promise((resolve,reject)=>{const r=db.transaction("reports").objectStore("reports").getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})},
  async put(value){const db=await this.open();return new Promise((resolve,reject)=>{const r=db.transaction("reports","readwrite").objectStore("reports").put(value);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})},
  async delete(id){const db=await this.open();return new Promise((resolve,reject)=>{const r=db.transaction("reports","readwrite").objectStore("reports").delete(id);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})}
};
const uid=()=>crypto.randomUUID?.()||`HX-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function newReport(){return{id:uid(),title:"Initial Condition Report",address:"",date:today(),type:"Initial condition",preparedFor:"",preparedBy:"",generalNotes:"",checklist:{},customRooms:{},observations:[],version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
function toast(message){const el=$("toast");el.textContent=message;el.classList.add("show");clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove("show"),2400)}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function slug(s){return(s||"property").replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").slice(0,50)}
async function saveCurrent(show=false){if(!current)return;syncForm();current.updatedAt=new Date().toISOString();await DB.put(current);const i=reports.findIndex(r=>r.id===current.id);if(i>=0)reports[i]=current;else reports.push(current);$("saveStatus").textContent="Saved on this device";if(show)toast("Report saved on this device")}
let saveTimer;function queueSave(){if(!current)return;$("saveStatus").textContent="Saving…";clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveCurrent(),350)}
function syncForm(){if(!current)return;current.title=$("reportTitle").value.trim()||"Untitled Condition Report";current.address=$("address").value.trim();current.date=$("reportDate").value;current.type=$("reportType").value;current.preparedFor=$("preparedFor").value.trim();current.preparedBy=$("preparedBy").value.trim();current.generalNotes=$("generalNotes").value.trim()}

function showHome(){saveCurrent();current=null;$("homeView").hidden=false;$("editorView").hidden=true;renderReports()}
function openEditor(report,step="details"){current=structuredClone(report);$("homeView").hidden=true;$("editorView").hidden=false;$("reportTitle").value=current.title||"";$("address").value=current.address||"";$("reportDate").value=current.date||today();$("reportType").value=current.type||"Initial condition";$("preparedFor").value=current.preparedFor||"";$("preparedBy").value=current.preparedBy||"";$("generalNotes").value=current.generalNotes||"";renderChecklist();renderObservations();goStep(step)}
async function createReport(){const report=newReport();await DB.put(report);reports.push(report);openEditor(report)}
function renderReports(filter=""){const q=filter.toLowerCase().trim();const list=reports.filter(r=>`${r.title} ${r.address} ${r.type}`.toLowerCase().includes(q)).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));$("reportList").innerHTML=list.map(r=>`<article class="report-card"><span class="report-type">${esc(r.type)}</span><h3>${esc(r.title)}</h3><p>${esc(r.address||"Address not entered")}</p><div class="report-meta"><span>${new Date(r.date||r.createdAt).toLocaleDateString("en-SG",{day:"numeric",month:"short",year:"numeric"})}</span><span>${r.observations?.length||0} observations</span></div><div class="card-actions"><button class="button secondary" data-open="${r.id}">Open report</button><button class="delete-button" data-delete="${r.id}" aria-label="Delete">Delete</button></div></article>`).join("");$("emptyState").hidden=reports.length>0||q;$("reportList").hidden=!list.length;document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openEditor(reports.find(r=>r.id===b.dataset.open)));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=async()=>{const r=reports.find(x=>x.id===b.dataset.delete);if(confirm(`Delete “${r.title}”? This cannot be undone unless you have a backup.`)){await DB.delete(r.id);reports=reports.filter(x=>x.id!==r.id);renderReports($("searchReports").value);toast("Report deleted")}})}
function goStep(step){currentStep=step;["details","checklist","observations","review"].forEach((s,i)=>{ $(`${s}Panel`).hidden=s!==step;const b=document.querySelector(`.step[data-step="${s}"]`);b.classList.toggle("active",s===step);if(s===step){$("mobileStepTitle").textContent=b.querySelector("strong").textContent;$("mobileStepCount").textContent=`${i+1} of 4`}});if(step==="review")renderReview();scrollTo({top:0,behavior:"smooth"})}
function renderChecklist(){current.customRooms??={};const rooms={...CHECKLIST,...current.customRooms},keys=Object.keys(rooms);$("checklistRooms").innerHTML=keys.map((room,idx)=>`<details class="room-card" ${idx<2?'open':''}><summary>${esc(room)}</summary><div class="room-items">${rooms[room].map(item=>{const v=current.checklist?.[room]?.[item]||{};return`<div class="check-row"><span>${esc(item)}</span><select data-check-room="${esc(room)}" data-check-item="${esc(item)}">${CONDITIONS.map(c=>`<option ${v.condition===c?'selected':''}>${esc(c||"Select condition")}</option>`).join('')}</select><input data-note-room="${esc(room)}" data-note-item="${esc(item)}" value="${esc(v.note||'')}" placeholder="Optional note" /></div>`}).join('')}</div></details>`).join("");document.querySelectorAll("[data-check-room]").forEach(el=>el.onchange=()=>updateCheck(el.dataset.checkRoom,el.dataset.checkItem,"condition",el.value==="Select condition"?"":el.value));document.querySelectorAll("[data-note-room]").forEach(el=>el.oninput=()=>updateCheck(el.dataset.noteRoom,el.dataset.noteItem,"note",el.value))}
function updateCheck(room,item,key,value){current.checklist[room]??={};current.checklist[room][item]??={};current.checklist[room][item][key]=value;queueSave()}
function addCustomRoom(){const name=prompt("Enter the room or area name:");if(!name?.trim())return;const item=prompt("Enter the first checklist item (for example, Floor):","General condition");if(!item?.trim())return;current.customRooms??={};current.customRooms[name.trim()]=[item.trim()];renderChecklist();queueSave();toast("Custom room added")}

function renderObservations(){const list=current.observations||[];$("observationEmpty").hidden=!!list.length;$("observationList").innerHTML=list.map((o,i)=>`<article class="observation-card"><div class="observation-head"><div><span class="room-chip">${esc(o.room)}</span><h3>${esc(o.comment)}</h3></div><div class="observation-actions"><button data-edit-observation="${i}">Edit</button><button data-remove-observation="${i}">Delete</button></div></div>${o.photos?.length?`<div class="observation-photos">${o.photos.map(p=>`<img src="${p.data}" alt="Condition evidence" />`).join('')}</div>`:''}</article>`).join("");document.querySelectorAll("[data-edit-observation]").forEach(b=>b.onclick=()=>openObservation(Number(b.dataset.editObservation)));document.querySelectorAll("[data-remove-observation]").forEach(b=>b.onclick=()=>{if(confirm("Delete this observation?")){current.observations.splice(Number(b.dataset.removeObservation),1);renderObservations();queueSave()}})}
function openObservation(index=null){editingObservation=index;const o=index===null?{room:ROOMS[0],comment:"",photos:[]} : current.observations[index];tempPhotos=structuredClone(o.photos||[]);$("observationDialogTitle").textContent=index===null?"Add observation":"Edit observation";$("observationRoom").innerHTML=ROOMS.map(r=>`<option ${o.room===r?'selected':''}>${r}</option>`).join("");const custom=!ROOMS.includes(o.room);if(custom)$("observationRoom").value="Others";$("otherRoomWrap").hidden=$("observationRoom").value!=="Others";$("otherRoom").value=custom?o.room:"";$("observationComment").value=o.comment||"";renderTempPhotos();$("observationDialog").showModal()}
function renderTempPhotos(){$("photoPreview").innerHTML=tempPhotos.map((p,i)=>`<div class="photo-tile"><img src="${p.data}" alt="Selected photo"><div class="photo-tile-actions"><button type="button" data-annotate="${i}">Mark up</button><button type="button" data-remove-photo="${i}">Remove</button></div></div>`).join("");document.querySelectorAll("[data-remove-photo]").forEach(b=>b.onclick=()=>{tempPhotos.splice(Number(b.dataset.removePhoto),1);renderTempPhotos()});document.querySelectorAll("[data-annotate]").forEach(b=>b.onclick=()=>openAnnotation(Number(b.dataset.annotate)))}
async function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=1800,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);resolve({id:uid(),name:file.name,data:canvas.toDataURL("image/jpeg",.82),annotated:false})};img.onerror=reject;img.src=url})}
async function addPhotos(files){const remaining=3-tempPhotos.length;if(remaining<=0)return toast("Maximum three photos per observation");for(const file of [...files].slice(0,remaining))tempPhotos.push(await compressImage(file));renderTempPhotos();if(files.length>remaining)toast("Only the first available photos were added")}
function saveObservation(e){e.preventDefault();const room=$("observationRoom").value==="Others"?$("otherRoom").value.trim():$("observationRoom").value,comment=$("observationComment").value.trim();if(!room)return toast("Enter a room or area");if(!comment)return toast("Enter an observation comment");const value={id:editingObservation===null?uid():current.observations[editingObservation].id,room,comment,photos:tempPhotos};if(editingObservation===null)current.observations.push(value);else current.observations[editingObservation]=value;$("observationDialog").close();renderObservations();queueSave();toast("Observation saved")}

function openAnnotation(index){annotationIndex=index;annotationHistory=[];const img=new Image();img.onload=()=>{const canvas=$("annotationCanvas"),maxW=1200,maxH=850,scale=Math.min(1,maxW/img.width,maxH/img.height);canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);annotationHistory.push(canvas.toDataURL());$("annotationDialog").showModal()};img.src=tempPhotos[index].data}
function canvasPoint(e){const c=$("annotationCanvas"),r=c.getBoundingClientRect(),t=e.touches?.[0]||e;return{x:(t.clientX-r.left)*c.width/r.width,y:(t.clientY-r.top)*c.height/r.height}}
function annotationStart(e){e.preventDefault();drawState={start:canvasPoint(e),base:$("annotationCanvas").toDataURL(),points:[canvasPoint(e)]}}
function annotationMove(e){if(!drawState)return;e.preventDefault();const c=$("annotationCanvas"),ctx=c.getContext("2d"),p=canvasPoint(e),img=new Image();img.onload=()=>{ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(img,0,0);ctx.strokeStyle=$("annotationColor").value;ctx.fillStyle=$("annotationColor").value;ctx.lineWidth=Math.max(4,c.width/180);ctx.lineCap="round";if(annotationTool==="draw"){drawState.points.push(p);ctx.beginPath();ctx.moveTo(drawState.points[0].x,drawState.points[0].y);drawState.points.slice(1).forEach(q=>ctx.lineTo(q.x,q.y));ctx.stroke()}else if(annotationTool==="circle"){const x=(drawState.start.x+p.x)/2,y=(drawState.start.y+p.y)/2,rx=Math.abs(p.x-drawState.start.x)/2,ry=Math.abs(p.y-drawState.start.y)/2;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.stroke()}else{ctx.beginPath();ctx.moveTo(drawState.start.x,drawState.start.y);ctx.lineTo(p.x,p.y);ctx.stroke();const angle=Math.atan2(p.y-drawState.start.y,p.x-drawState.start.x),size=18+c.width/100;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x-size*Math.cos(angle-Math.PI/6),p.y-size*Math.sin(angle-Math.PI/6));ctx.lineTo(p.x-size*Math.cos(angle+Math.PI/6),p.y-size*Math.sin(angle+Math.PI/6));ctx.closePath();ctx.fill()}};img.src=drawState.base}
function annotationEnd(){if(!drawState)return;annotationHistory.push($("annotationCanvas").toDataURL());drawState=null}
function restoreCanvas(data){const img=new Image();img.onload=()=>{$("annotationCanvas").getContext("2d").drawImage(img,0,0)};img.src=data}

function renderReview(){syncForm();const checked=Object.values(current.checklist||{}).reduce((n,r)=>n+Object.values(r).filter(x=>x.condition).length,0),photos=current.observations.reduce((n,o)=>n+(o.photos?.length||0),0);$("reviewSummary").innerHTML=`<div class="summary-card"><span>Checklist items</span><strong>${checked}</strong></div><div class="summary-card"><span>Observations</span><strong>${current.observations.length}</strong></div><div class="summary-card"><span>Photos</span><strong>${photos}</strong></div><div class="summary-card report-overview"><span>Report</span><strong>${esc(current.title)}</strong><p>${esc(current.address||"Address not entered")} · ${esc(current.type)} · ${esc(current.date)}</p></div>`}
async function sha(text){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return[...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function generatePdf(){if(!current.address)return toast("Add the property address before exporting");await saveCurrent();const {PDFDocument,StandardFonts,rgb}=PDFLib,pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),W=595,H=842,margin=48,green=rgb(.07,.21,.18),rust=rgb(.78,.36,.23),ink=rgb(.08,.14,.12),muted=rgb(.37,.43,.40),line=rgb(.84,.85,.82),generated=new Date(),fingerprint=(await sha(JSON.stringify(current)+generated.toISOString())).slice(0,16).toUpperCase();let page,y;
  const addPage=()=>{page=pdf.addPage([W,H]);y=H-margin;page.drawText("HANDOVERX",{x:margin,y:H-30,size:8,font:bold,color:green});page.drawText(`Report ${current.id.slice(0,8).toUpperCase()}  ·  Version ${current.version}`,{x:W-margin-170,y:H-30,size:7,font:regular,color:muted});page.drawLine({start:{x:margin,y:H-37},end:{x:W-margin,y:H-37},thickness:.6,color:line});page.drawText(`Generated ${generated.toLocaleString("en-SG")}  ·  ${fingerprint}`,{x:margin,y:19,size:6.5,font:regular,color:muted});page.drawText(`${pdf.getPageCount()}`,{x:W-margin-10,y:19,size:7,font:regular,color:muted});return page};
  const ensure=h=>{if(y-h<44)addPage()};const wrap=(text,max,size=10,f=regular)=>{const words=String(text||"").replace(/[^\x20-\x7E]/g,"-").split(/\s+/),lines=[];let l="";for(const w of words){const n=l?`${l} ${w}`:w;if(f.widthOfTextAtSize(n,size)>max){if(l)lines.push(l);l=w}else l=n}if(l)lines.push(l);return lines};const text=(value,x,size=10,f=regular,color=ink,max=W-margin*2,leading=size*1.35)=>{const lines=wrap(value,max,size,f);ensure(lines.length*leading+4);for(const l of lines){page.drawText(l,{x,y,size,font:f,color});y-=leading}return lines.length};const label=value=>{ensure(26);page.drawText(value.toUpperCase(),{x:margin,y,size:7.5,font:bold,color:rust});y-=17};const heading=value=>{ensure(36);text(value,margin,18,bold,ink);y-=8};
  page=pdf.addPage([W,H]);page.drawRectangle({x:0,y:0,width:W,height:H,color:green});page.drawText("HANDOVERX",{x:margin,y:H-65,size:12,font:bold,color:rgb(.78,.92,.87)});page.drawText("RESIDENTIAL",{x:margin,y:H-205,size:11,font:bold,color:rgb(.55,.78,.70)});page.drawText("CONDITION",{x:margin,y:H-254,size:38,font:bold,color:rgb(1,1,1)});page.drawText("REPORT",{x:margin,y:H-299,size:38,font:bold,color:rgb(1,1,1)});let coverY=H-370;for(const l of wrap(current.address,W-margin*2,15,bold)){page.drawText(l,{x:margin,y:coverY,size:15,font:bold,color:rgb(.9,.94,.92)});coverY-=21}page.drawLine({start:{x:margin,y:115},end:{x:W-margin,y:115},thickness:.7,color:rgb(.35,.55,.48)});page.drawText(current.title,{x:margin,y:88,size:12,font:bold,color:rgb(1,1,1)});page.drawText(`${current.type}  ·  ${current.date}`,{x:margin,y:68,size:9,font:regular,color:rgb(.72,.83,.79)});page.drawText(`Report ID ${current.id.toUpperCase()}`,{x:margin,y:48,size:7,font:regular,color:rgb(.55,.7,.65)});
  addPage();label("Report information");heading(current.title);const fields=[["PROPERTY",current.address],["REPORT DATE",current.date],["REPORT TYPE",current.type],["PREPARED FOR",current.preparedFor||"Not stated"],["PREPARED BY",current.preparedBy||"Not stated"]];for(const [k,v] of fields){ensure(42);page.drawText(k,{x:margin,y,size:7,font:bold,color:muted});text(v,margin+105,10,k==="PROPERTY"?bold:regular,ink,W-margin*2-105);y-=9}if(current.generalNotes){y-=8;label("General notes");text(current.generalNotes,margin,10,regular,ink);y-=8}
  const activeRooms=Object.entries(current.checklist||{}).filter(([,items])=>Object.values(items).some(v=>v.condition||v.note));if(activeRooms.length){label("Room checklist");for(const [room,items] of activeRooms){ensure(35);text(room,margin,12,bold,green);y-=4;for(const [item,v] of Object.entries(items).filter(([,x])=>x.condition||x.note)){ensure(23);page.drawText(item,{x:margin,y,size:8.5,font:bold,color:ink});page.drawText(v.condition||"-",{x:margin+170,y,size:8.5,font:regular,color:green});if(v.note)page.drawText(wrap(v.note,180,8)[0]||"",{x:margin+320,y,size:8,font:regular,color:muted});y-=17}y-=8}}
  if(current.observations.length){addPage();label("Photo observations");heading("Recorded conditions");for(let i=0;i<current.observations.length;i++){const o=current.observations[i];ensure(65);page.drawText(String(i+1).padStart(2,"0"),{x:margin,y,size:9,font:bold,color:rust});page.drawText(o.room.toUpperCase(),{x:margin+30,y,size:8,font:bold,color:green});y-=18;text(o.comment,margin+30,10,bold,ink,W-margin*2-30);y-=8;if(o.photos?.length){for(const p of o.photos){ensure(230);try{const bytes=await fetch(p.data).then(r=>r.arrayBuffer()),img=p.data.startsWith("data:image/png")?await pdf.embedPng(bytes):await pdf.embedJpg(bytes),dims=img.scale(1),maxW=W-margin*2-30,maxH=220,scale=Math.min(maxW/dims.width,maxH/dims.height);page.drawImage(img,{x:margin+30,y:y-dims.height*scale,width:dims.width*scale,height:dims.height*scale});y-=dims.height*scale+12}catch{}}}y-=12}}
  addPage();label("Important information");heading("Scope and limitations");text("This residential condition record is a dated visual reference of observable surface conditions at the property. It is not a warranty, specialist inspection, valuation, repair quotation or confirmation that concealed services comply with current standards.",margin,9.5,regular,ink);y-=12;text("The inspection does not include moving furniture, lifting floor coverings, opening secured panels, dismantling fittings or testing inaccessible systems. Photographs and comments should be read together with the room checklist and general notes.",margin,9.5,regular,ink);y-=20;page.drawRectangle({x:margin,y:y-70,width:W-margin*2,height:70,color:rgb(.94,.96,.94)});page.drawText("DOCUMENT RECORD",{x:margin+16,y:y-19,size:7,font:bold,color:muted});page.drawText(`Report ID: ${current.id.toUpperCase()}`,{x:margin+16,y:y-37,size:8,font:regular,color:ink});page.drawText(`Version: ${current.version}   Fingerprint: ${fingerprint}`,{x:margin+16,y:y-53,size:8,font:regular,color:ink});
  const bytes=await pdf.save();download(new Blob([bytes],{type:"application/pdf"}),`HandoverX_${slug(current.address)}_${slug(current.title)}_v${current.version}.pdf`);current.version=(current.version||1)+1;await saveCurrent();toast("PDF downloaded")}

function exportData(data,name){download(new Blob([JSON.stringify({app:"HandoverX",exportedAt:new Date().toISOString(),reports:data},null,2)],{type:"application/json"}),name)}
async function importData(file){try{const json=JSON.parse(await file.text()),incoming=Array.isArray(json.reports)?json.reports:[json.reports];if(!incoming.length)throw Error();for(const r of incoming){if(!r?.id)r.id=uid();await DB.put(r);const i=reports.findIndex(x=>x.id===r.id);if(i>=0)reports[i]=r;else reports.push(r)}renderReports();toast(`${incoming.length} report${incoming.length===1?'':'s'} restored`)}catch{toast("That backup file could not be read")}}

function bind(){[$("newReportTop"),$("newReportHero"),$("emptyCreate")].forEach(b=>b.onclick=createReport);$("backHome").onclick=$("mobileBack").onclick=showHome;document.querySelectorAll(".step").forEach(b=>b.onclick=()=>{saveCurrent();goStep(b.dataset.step)});document.querySelectorAll("[data-next]").forEach(b=>b.onclick=()=>{saveCurrent();goStep(b.dataset.next)});document.querySelectorAll("[data-prev]").forEach(b=>b.onclick=()=>goStep(b.dataset.prev));["reportTitle","address","reportDate","reportType","preparedFor","preparedBy","generalNotes"].forEach(id=>$(id).addEventListener("input",queueSave));$("searchReports").oninput=e=>renderReports(e.target.value);$("addCustomRoom").onclick=addCustomRoom;$("addObservation").onclick=$("emptyAddObservation").onclick=()=>openObservation();$("observationRoom").onchange=e=>$("otherRoomWrap").hidden=e.target.value!=="Others";$("photoInput").onchange=e=>addPhotos(e.target.files);$("saveObservation").onclick=saveObservation;$("generatePdf").onclick=generatePdf;$("finishReport").onclick=showHome;$("duplicateReport").onclick=async()=>{const copy=structuredClone(current);copy.id=uid();copy.title=`${current.title} - Copy`;copy.version=1;copy.createdAt=copy.updatedAt=new Date().toISOString();await DB.put(copy);reports.push(copy);openEditor(copy);toast("Separate report created")};$("backupReport").onclick=()=>exportData([current],`HandoverX_${slug(current.address)}_backup.handoverx`);$("backupAll").onclick=()=>exportData(reports,"HandoverX_all_reports_backup.handoverx");$("importButton").onclick=()=>$("importInput").click();$("importInput").onchange=e=>importData(e.target.files[0]);$("annotationCanvas").addEventListener("pointerdown",annotationStart);$("annotationCanvas").addEventListener("pointermove",annotationMove);window.addEventListener("pointerup",annotationEnd);document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{annotationTool=b.dataset.tool;document.querySelectorAll("[data-tool]").forEach(x=>x.classList.toggle("active",x===b))});$("undoAnnotation").onclick=()=>{if(annotationHistory.length>1){annotationHistory.pop();restoreCanvas(annotationHistory.at(-1))}};$("clearAnnotation").onclick=()=>{annotationHistory=[annotationHistory[0]];restoreCanvas(annotationHistory[0])};$("saveAnnotation").onclick=()=>{tempPhotos[annotationIndex].data=$("annotationCanvas").toDataURL("image/jpeg",.9);tempPhotos[annotationIndex].annotated=true;$("annotationDialog").close();renderTempPhotos();toast("Photo markup saved")};[$("closeAnnotation"),$("cancelAnnotation")].forEach(b=>b.onclick=()=>$("annotationDialog").close());document.querySelector(".brand").onclick=showHome;window.addEventListener("beforeunload",()=>{if(current)DB.put(current)})}
async function init(){bind();try{reports=await DB.all();renderReports();if(navigator.storage?.persist)navigator.storage.persist();if("serviceWorker"in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("./service-worker.js")}catch(e){console.error(e);toast("Local storage is unavailable in this browser")}}
init();
